import { Poppins } from 'next/font/google'
import '@/styles/global.scss'
import { AuthProvider } from './Providers'
import { Toaster } from 'sonner';
import Header from '@/components/header';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
        <Toaster theme='dark' position='top-right' visibleToasts={4} dir='auto' richColors />
      </body>
    </html>
  )
}
